//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebCalculadora.CalculaAreas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculaAreas.CalcularAreaSoap")]
    public interface CalcularAreaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        double AreaCuadrado(double number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AreaCuadradoAsync(double number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        double AreaTriangulo(double bases, double altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AreaTrianguloAsync(double bases, double altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        double AreaCirculo(double radio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AreaCirculoAsync(double radio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcularAreaSoapChannel : ServicioWebCalculadora.CalculaAreas.CalcularAreaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcularAreaSoapClient : System.ServiceModel.ClientBase<ServicioWebCalculadora.CalculaAreas.CalcularAreaSoap>, ServicioWebCalculadora.CalculaAreas.CalcularAreaSoap {
        
        public CalcularAreaSoapClient() {
        }
        
        public CalcularAreaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcularAreaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcularAreaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcularAreaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AreaCuadrado(double number) {
            return base.Channel.AreaCuadrado(number);
        }
        
        public System.Threading.Tasks.Task<double> AreaCuadradoAsync(double number) {
            return base.Channel.AreaCuadradoAsync(number);
        }
        
        public double AreaTriangulo(double bases, double altura) {
            return base.Channel.AreaTriangulo(bases, altura);
        }
        
        public System.Threading.Tasks.Task<double> AreaTrianguloAsync(double bases, double altura) {
            return base.Channel.AreaTrianguloAsync(bases, altura);
        }
        
        public double AreaCirculo(double radio) {
            return base.Channel.AreaCirculo(radio);
        }
        
        public System.Threading.Tasks.Task<double> AreaCirculoAsync(double radio) {
            return base.Channel.AreaCirculoAsync(radio);
        }
    }
}
